### ISSUE TITLE
Check if CastVote etc is needed

### ISSUE THREAD

**Issue by JennStro** [chris2402/PollApplication#31]
Check if `@PostMapping()
    public Boolean castVote(@Valid @RequestBody CastVoteRequest castVoteRequest){
        return voteService.vote(castVoteRequest);
    }` 

can be changed to  

`@PostMapping()
    public Boolean placeVote(@Valid @RequestBody vote){
        return voteService.vote(vote);
    }`

**Comment by oddhus** [comment]
When receiving a request and mapping the Requestbody, spring boot can not convert the integers pollId and userId to classes Voter and User. We therefore need the castvoterequest.
