### ISSUE TITLE
Test business logic

### ISSUE THREAD

**Issue by JennStro** [chris2402/PollApplication#39]
Test the services of the application, where the business logic resides. 

**GuestService**  

- [ ] You can get a list of all guests   

- [ ] You can create a new guest 

**PollService**  

- [ ] A user can create a new poll  

- [ ] A user can delete a poll  

- [ ] You can get all public polls 

- [ ] A owner or admin can change poll  

- [ ] You can get number of votes from a poll

**Comment by oddhus** [comment]
duplicate
