### ISSUE TITLE
Discuss PUT vs PATCH

### ISSUE THREAD

**Issue by JennStro** [chris2402/PollApplication#69]
https://stackoverflow.com/questions/28459418/use-of-put-vs-patch-methods-in-rest-api-real-life-scenarios   

Should we replace the whole entity when updating or only password in user? 

` { password: oldpassword, newpassword: newpassword }`

**Comment by oddhus** [comment]
Prøvde å lese litt på det, men skjønner det ikke helt 😄. Hvorfor vi vil bytte ut hele entiteten hvis vi vil forandre et felt?

Slik som jeg forstår det bruker man PUT for å sikre "idempotent", ved å sende alle feltene og bytte ut hele entiteten. Hvis noen av feltene mangler, setter du dem til null. Da er du sikker på hvordan den ser ut. (Hvordan ville vi byttet ut referansene?)

En PATCH-request er du ikke sikret at er idempotent, men du kan implementere den slik at den er det. Det tror jeg vi har gjort, fordi uansett hvor mange ganger du sender updateUser PATCH request forandrer bare de feltene vi ønsker at skal gjøre det, og ikke selve ressursen seg.

Det kan være noe jeg har misforstått 🤔

**Comment by JennStro** [comment]
> Prøvde å lese litt på det, men skjønner det ikke helt 😄. Hvorfor vi vil bytte ut hele entiteten hvis vi vil forandre et felt?
> 

Ja, helt enig her! Men ble usikker på om vi skal ha username med da også? eller om vi bare skal ha det gamle passordet og nye passordet? For nå sender vi `{ username: user, password: oldpassword, newpassword: newpassword }`, som en UpdateUserRequest, ikke bare passordet (som er det som endres) :) Jeg skjønner det ikke helt jeg heller hah, har ikke sett patch før 🤦‍♀️

**Comment by oddhus** [comment]
En bruker kan oppdatere passordet eller brukernavnet. I stedet for å lage to ulike requestklasser og metoder tenke jeg at det kunne være lurt å ha begge i en. Hvis man ikke inkluderer brukernavnet oppdaterer ikke UpdateUserRequest brukernavnet. Det vil altså ikke bli satt til null. Dermed kan man velge hva man vil oppdater utfra hvilke felter man inkluderer. 

Usikker på om dette er normen eller rett måte å gjøre det på, men virket naturlig i vårt tilfelle 😄
