### ISSUE TITLE
Document API with swagger or JavaDocs

### ISSUE THREAD

**Issue by JennStro** [chris2402/PollApplication#79]

**Comment by oddhus** [comment]
Hvis vi ikke inkluderer spring-boot-starter-rest. Fungerer det som forventet, da vil den ikke lage "HATEOAS" :) 
![image](https://user-images.githubusercontent.com/51832618/94906568-fe234400-049e-11eb-8bbf-451791f30bd0.png)

**Comment by JennStro** [comment]
Kjempebra at du fant ut av dette! 😃 🎖️ 🔥

**Comment by oddhus** [comment]
Og alt kjører fortsatt like fint, så vi trenger tydeligvis ikke den pakken 😄
