### ISSUE TITLE
votes do not get added to poll when saved in voteRepository

### ISSUE THREAD

**Issue by JennStro** [chris2402/PollApplication#81]
`vote.setPoll(poll); voteRepository.save(vote);` does not link the vote to given poll: `pollRepository.getPollById(poll.getId()).get().getVotes().size()` fails and the poll have zero votes. 

**Solution**    
We need to add functionality to add votes to poll and then persist it. The same for user. (I am on it) 😎

**Comment by oddhus** [comment]
Det var merkelig 🤔 . Castvote i voteservice lagrer vote i voterepository og det fungerer fint i postman. Det går vertfall an å hente de ut når vi teller votes i get poll result. Kan det være noe som skjer i testmiljøet?

**Comment by JennStro** [comment]
Det virket ikke når jeg skrev en test for voteRepository, så det burde jo funke.. Tror vi har gjort noe feil med relasjonene egentlig, siden Votes -> Poll er definert som en bidirectional relasjon men den er vel en unidirectional relasjon? Samme med user og polls egentlig. Ser litt på det nå, er samme problemet med at pollRepo.save(poll) ikke kobler seg til en user

**Comment by oddhus** [comment]
Tror jeg fant ut grunnen 😄 Det er fordi vi må alltid lagre den entiteten som eier forholdet, det vil si den som har mappedBy i annonteringen.

Når det gjelder de bidirectionale forholdene er det vel lurt ha dem, slik at vi kan bevege oss fra en voter til vote til poll og omvendt vei fra poll til vote til voter. Fant også en [artikkel](https://thorben-janssen.com/best-practices-many-one-one-many-associations-mappings/) som nevner dette

**Comment by JennStro** [comment]
Okay! 😁 Men da er det ikke nok å kalle på voteRepository.savePoll(), men man må også kalle på pollRepository.save(poll)? Har stresset litt med det nå så det var bra du så.

Ja er enig med bidirectional forhold mellom voter og poll, men f. Eks en poll og user trenger bare unidirectional forhold.  Edit: ser nå at artikkelen fraråder det uansett, ble litt forvirret nå egentlig siden har fått inntrykk av at biderectional forhold mapper til et "mange til mange" forhold, mens vi har "en til mange" forhold mellom user og poll 🤔😬

**Comment by oddhus** [comment]
Ja, det viker som om du har rett i at den på en måte mapper et mange til mange forhold selv om du bare har et én til mange forhold. Det visste jeg ikke, men ser ut som det er  mulig å unngå det. Fra artikkelen:

> So, Hibernate introduces an association table to store the foreign keys.
> You can avoid this table if you specify the foreign key column with a @JoinColumn annotation.

Ja, jeg tror man må gjøre det nesten slik som du beskriver det, men siden vi har  `cascadetype = cascade.ALL` i poll trenger vi bare å gjøre slik:
`poll.getVotes().add(vote)` <-- Hmm, lurer på om den måte hente alle votes hver gang vi legger til en vote her 🤔 
`pollRepository.save(poll)`

Vi trenger derfor ikke å bruke, `voteRepository.save()`. Tror jeg, hvis jeg har for stått det rett 😬

**Comment by JennStro** [comment]
Jeg prøvde meg litt frem og har laget en metode poll.add(vote) som bare legger til en vote i listen, og for user.add(poll). Det tror jeg funker, men skal se nærmere på det imorgen 😁

**Comment by JennStro** [comment]
Hvis du ser på PR #80 så ser du hva jeg måtte legge til for at det virker. Da kan vi bruke både `vote.setPoll(poll); voteRepository.save(vote)` og `poll.add(vote); pollRepository.save(poll)` og pollen blir knyttet til voten, så da funker det som det skal uten at vi trenger å andre på noe kode (alt kjører grønt hverfall, også testen om at en poll har en vote etter at voteRepository.save(vote) er kalt). Puh! 💯 Vi burde gjøre det samme for Poll og User også men det får bli i en annen PR 👍
